# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ddirmultinomial_cpp <- function(x, n, alpha, log) {
    .Call(`_HBMAP_ddirmultinomial_cpp`, x, n, alpha, log)
}

compute_probability_cpp <- function(Y, omega_M, q_star_1_J, gamma_1_J_star) {
    .Call(`_HBMAP_compute_probability_cpp`, Y, omega_M, q_star_1_J, gamma_1_J_star)
}

draw_cat <- function(prob) {
    .Call(`_HBMAP_draw_cat`, prob)
}

Z_sample_cpp <- function(Prob) {
    .Call(`_HBMAP_Z_sample_cpp`, Prob)
}

q_star_logprob_cpp <- function(Y_sub, q_j_star, gamma_j_star, alpha_h) {
    .Call(`_HBMAP_q_star_logprob_cpp`, Y_sub, q_j_star, gamma_j_star, alpha_h)
}

gamma_logprob_cpp <- function(Y_sub, q_j_star, gamma_j_star, a_gamma, b_gamma, lb_gamma) {
    .Call(`_HBMAP_gamma_logprob_cpp`, Y_sub, q_j_star, gamma_j_star, a_gamma, b_gamma, lb_gamma)
}

